// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcjXijSQ8UFillMoNUKN6VDGCLP1psC0o',
    appId: '1:691538021682:web:5699340a5e3578d0ac9b2b',
    messagingSenderId: '691538021682',
    projectId: 'trackcreditapp',
    authDomain: 'trackcreditapp.firebaseapp.com',
    storageBucket: 'trackcreditapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0zu_wWCZn8RZCuRHin-IraKEtP4OwAfE',
    appId: '1:691538021682:android:fba4ed6bac081846ac9b2b',
    messagingSenderId: '691538021682',
    projectId: 'trackcreditapp',
    storageBucket: 'trackcreditapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGyAAedYhD1eNvOB5E6Bwlk-z6WVLt96w',
    appId: '1:691538021682:ios:66477b363146798cac9b2b',
    messagingSenderId: '691538021682',
    projectId: 'trackcreditapp',
    storageBucket: 'trackcreditapp.appspot.com',
    iosBundleId: 'com.example.trackcreditapp',
  );

}